services:
  - type: web
    name: vad-food-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python api.py"
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: WEATHER_API_KEY
        sync: false
    plan: free
